# Generated by Django 5.1.6 on 2025-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Plot', 'Plot'), ('Commercial', 'Commercial Space')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.FloatField()),
                ('furnishing', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], default='Unfurnished', max_length=20)),
                ('availability', models.CharField(choices=[('Immediate', 'Immediate'), ('Within 1 Month', 'Within 1 Month'), ('Within 3 Months', 'Within 3 Months'), ('After 3 Months', 'After 3 Months')], default='Immediate', max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
